// Code generated by the origin_data import; DO NOT EDIT.

package yingang

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() { core.RegisterWeaponFunc(keys.Yingang, NewWeapon) }
