#!/usr/bin/env python3
"""Generate verified talent arrays and explicit basic actions for imported characters."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "character_imports/manifest.json"
ELEMENTS = {
    "Anemo": "Anemo", "Geo": "Geo", "Electro": "Electro", "Dendro": "Dendro",
    "Cryo": "Cryo", "Pyro": "Pyro", "Hydro": "Hydro",
}


def go_name(slug: str) -> str:
    return "".join(x.capitalize() for x in re.split(r"[^a-zA-Z0-9]", slug))


def levels(skill: dict) -> list[dict]:
    return [skill["promote"][str(i)] for i in range(15)]


def param_indexes(label: str) -> list[int]:
    result = [int(x) - 1 for x in re.findall(r"\{param(\d+)", label)]
    if len(result) == 1:
        mult = re.search(r"[×x](\d+)", label)
        if mult:
            result *= int(mult.group(1))
    return result


def arrays_for_label(skill: dict, label: str) -> list[list[float]]:
    return [
        [level["param"][idx] for level in levels(skill)]
        for idx in param_indexes(label)
    ]


def go_array(values: list[float]) -> str:
    return "[]float64{" + ", ".join(f"{x:.9g}" for x in values) + "}"


def go_nested(groups: list[list[list[float]]]) -> str:
    stages = []
    for group in groups:
        stages.append("{" + ", ".join(go_array(values) for values in group) + "}")
    return "[][][]float64{" + ", ".join(stages) + "}"


def talent_data(record: dict) -> dict:
    attack, skill, burst = record["implementation_inputs"]["confirmed"]["combat_tables"]["skills"]
    attack_labels = levels(attack)[0]["desc"]
    normal = []
    for label in attack_labels:
        if re.match(r"\d+-Hit DMG", label):
            normal.append(arrays_for_label(attack, label))
    charge_labels = [
        x for x in attack_labels
        if x.startswith("Charged Attack DMG") or x.startswith("Aimed Shot") or x.startswith("Fully-Charged Aimed Shot")
    ]
    charge = [values for label in charge_labels for values in arrays_for_label(attack, label)]
    plunge_label = next((x for x in attack_labels if x.startswith("Plunge DMG")), "")
    collision = arrays_for_label(attack, plunge_label)
    low_high_label = next((x for x in attack_labels if x.startswith("Low/High Plunge DMG")), "")
    low_high = arrays_for_label(attack, low_high_label)

    def damage_arrays(talent: dict) -> list[list[float]]:
        result = []
        for label in levels(talent)[0]["desc"]:
            if "DMG" not in label or not param_indexes(label):
                continue
            for values in arrays_for_label(talent, label):
                result.append(values)
        return result

    return {
        "normal": normal,
        "charge": charge,
        "collision": collision[0] if collision else [0.0] * 15,
        "low": low_high[0] if low_high else [0.0] * 15,
        "high": low_high[1] if len(low_high) > 1 else (low_high[0] if low_high else [0.0] * 15),
        "skill": damage_arrays(skill),
        "burst": damage_arrays(burst),
        "skill_params": [
            [level["param"][i] for level in levels(skill)]
            for i in range(len(levels(skill)[0]["param"]))
        ],
        "burst_params": [
            [level["param"][i] for level in levels(burst)]
            for i in range(len(levels(burst)[0]["param"]))
        ],
    }


def write_generated(entry: dict, record: dict, data: dict) -> None:
    slug = entry["name"]
    skill_arrays = ", ".join(go_array(x) for x in data["skill"]) or go_array([0.0] * 15)
    burst_arrays = ", ".join(go_array(x) for x in data["burst"]) or go_array([0.0] * 15)
    skill_params = ", ".join(go_array(x) for x in data["skill_params"])
    burst_params = ", ".join(go_array(x) for x in data["burst_params"])
    output = f"""// Code generated by scripts/generate_imported_character_actions.py; DO NOT EDIT.

package {slug}

import (
\t"github.com/genshinsim/gcsim/pkg/core"
\t"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {{ core.RegisterCharFunc(keys.{go_name(slug)}, NewChar) }}

var attack = {go_nested(data["normal"])}
var charge = [][]float64{{{", ".join(go_array(x) for x in data["charge"])}}}
var collision = {go_array(data["collision"])}
var lowPlunge = {go_array(data["low"])}
var highPlunge = {go_array(data["high"])}
var skill = [][]float64{{{skill_arrays}}}
var burst = [][]float64{{{burst_arrays}}}
var skillParam = [][]float64{{{skill_params}}}
var burstParam = [][]float64{{{burst_params}}}
"""
    (ROOT / "internal/characters" / slug / f"zz_{slug}.dm.go").write_text(output)


def strike_type(weapon: str) -> str:
    if weapon == "Claymore":
        return "attacks.StrikeTypeBlunt"
    if weapon in ("Polearm", "Bow"):
        return "attacks.StrikeTypePierce"
    return "attacks.StrikeTypeDefault"


def normal_element(entry: dict) -> str:
    return f"attributes.{entry['element']}" if entry["weapon"] == "Catalyst" else "attributes.Physical"


def charged_element(entry: dict) -> str:
    return f"attributes.{entry['element']}" if entry["weapon"] in ("Catalyst", "Bow") else "attributes.Physical"


def write_base(entry: dict, record: dict, normal_count: int) -> None:
    slug = entry["name"]
    tables = record["implementation_inputs"]["confirmed"]["combat_tables"]
    burst_desc = levels(tables["skills"][2])[0]
    energy = 0
    for label in burst_desc["desc"]:
        if "Energy Cost" in label:
            indexes = param_indexes(label)
            if indexes:
                energy = burst_desc["param"][indexes[0]]
    output = f"""package {slug}

import (
\ttmpl "github.com/genshinsim/gcsim/internal/template/character"
\t"github.com/genshinsim/gcsim/pkg/core"
\t"github.com/genshinsim/gcsim/pkg/core/info"
\t"github.com/genshinsim/gcsim/pkg/core/player/character"
)

type char struct {{
\t*tmpl.Character
}}

func NewChar(s *core.Core, w *character.CharWrapper, _ info.CharacterProfile) error {{
\tc := &char{{Character: tmpl.NewWithWrapper(s, w)}}
\tc.EnergyMax = {energy}
\tc.NormalHitNum = {normal_count}
\tc.SkillCon = 3
\tc.BurstCon = 5
\tw.Character = c
\treturn nil
}}

func (c *char) Init() error {{
\tc.initAscensions()
\tc.initConstellations()
\treturn nil
}}
"""
    (ROOT / "internal/characters" / slug / f"{slug}.go").write_text(output)


def write_attack(entry: dict) -> None:
    slug = entry["name"]
    output = f"""package {slug}

import (
\t"fmt"
\t"github.com/genshinsim/gcsim/internal/frames"
\t"github.com/genshinsim/gcsim/pkg/core/action"
\t"github.com/genshinsim/gcsim/pkg/core/attacks"
\t"github.com/genshinsim/gcsim/pkg/core/attributes"
\t"github.com/genshinsim/gcsim/pkg/core/combat"
\t"github.com/genshinsim/gcsim/pkg/core/info"
)

// TODO: replace conservative hitmarks/cancels when verified frame data is available.
func (c *char) Attack(map[string]int) (action.Info, error) {{
\tstage := c.NormalCounter
\tfor hit, mult := range attack[stage] {{
\t\tai := info.AttackInfo{{
\t\t\tActorIndex: c.Index(), Abil: fmt.Sprintf("Normal %d-%d", stage+1, hit+1),
\t\t\tAttackTag: attacks.AttackTagNormal, ICDTag: attacks.ICDTagNormalAttack,
\t\t\tICDGroup: attacks.ICDGroupDefault, StrikeType: {strike_type(entry["weapon"])},
\t\t\tElement: {normal_element(entry)}, Durability: 25, Mult: mult[c.TalentLvlAttack()],
\t\t}}
\t\tc.Core.QueueAttack(ai, combat.NewCircleHitOnTarget(c.Core.Combat.PrimaryTarget(), nil, 1.5), 18+hit*6, 18+hit*6)
\t}}
\tc.AdvanceNormalIndex()
\tf := frames.InitNormalCancelSlice(18+(len(attack[stage])-1)*6, 42)
\treturn action.Info{{Frames: frames.NewAbilFunc(f), AnimationLength: 42, CanQueueAfter: 18, State: action.NormalAttackState}}, nil
}}
"""
    (ROOT / "internal/characters" / slug / "attack.go").write_text(output)


def write_charge(entry: dict) -> None:
    slug = entry["name"]
    charge_loop = "charge"
    if entry["weapon"] == "Bow":
        # Bow charge arrays include the uncharged aimed shot followed by the
        # fully charged elemental shot. ChargeAttack represents the latter.
        charge_loop = "charge[len(charge)-1:]"
    output = f"""package {slug}

import (
\t"github.com/genshinsim/gcsim/internal/frames"
\t"github.com/genshinsim/gcsim/pkg/core/action"
\t"github.com/genshinsim/gcsim/pkg/core/attacks"
\t"github.com/genshinsim/gcsim/pkg/core/attributes"
\t"github.com/genshinsim/gcsim/pkg/core/combat"
\t"github.com/genshinsim/gcsim/pkg/core/info"
)

// TODO: replace conservative hitmarks/cancels when verified frame data is available.
func (c *char) ChargeAttack(map[string]int) (action.Info, error) {{
\tfor hit, mult := range {charge_loop} {{
\t\tai := info.AttackInfo{{
\t\t\tActorIndex: c.Index(), Abil: "Charged Attack", AttackTag: attacks.AttackTagExtra,
\t\t\tICDTag: attacks.ICDTagNormalAttack, ICDGroup: attacks.ICDGroupDefault,
\t\t\tStrikeType: {strike_type(entry["weapon"])}, Element: {charged_element(entry)},
\t\t\tDurability: 25, Mult: mult[c.TalentLvlAttack()],
\t\t}}
\t\tc.Core.QueueAttack(ai, combat.NewCircleHitOnTarget(c.Core.Combat.PrimaryTarget(), nil, 2), 30+hit*6, 30+hit*6)
\t}}
\tf := frames.InitAbilSlice(52)
\treturn action.Info{{Frames: frames.NewAbilFunc(f), AnimationLength: 52, CanQueueAfter: 36, State: action.ChargeAttackState}}, nil
}}
"""
    (ROOT / "internal/characters" / slug / "charge.go").write_text(output)


def write_plunge(entry: dict) -> None:
    slug = entry["name"]
    element = f"attributes.{entry['element']}" if entry["weapon"] == "Catalyst" else "attributes.Physical"
    output = f"""package {slug}

import (
\t"github.com/genshinsim/gcsim/internal/frames"
\t"github.com/genshinsim/gcsim/pkg/core/action"
\t"github.com/genshinsim/gcsim/pkg/core/attacks"
\t"github.com/genshinsim/gcsim/pkg/core/attributes"
\t"github.com/genshinsim/gcsim/pkg/core/combat"
\t"github.com/genshinsim/gcsim/pkg/core/info"
\t"github.com/genshinsim/gcsim/pkg/core/player"
)

func (c *char) LowPlungeAttack(p map[string]int) (action.Info, error) {{ return c.plunge(p, false) }}
func (c *char) HighPlungeAttack(p map[string]int) (action.Info, error) {{ return c.plunge(p, true) }}

// TODO: replace conservative hitmarks/cancels when verified frame data is available.
func (c *char) plunge(p map[string]int, high bool) (action.Info, error) {{
\tc.Core.Player.SetAirborne(player.Grounded)
\tif p["collision"] != 0 {{
\t\tai := info.AttackInfo{{ActorIndex: c.Index(), Abil: "Plunge Collision", AttackTag: attacks.AttackTagPlunge, ICDTag: attacks.ICDTagNone, ICDGroup: attacks.ICDGroupDefault, StrikeType: {strike_type(entry["weapon"])}, Element: {element}, Mult: collision[c.TalentLvlAttack()]}}
\t\tc.Core.QueueAttack(ai, combat.NewCircleHitOnTarget(c.Core.Combat.PrimaryTarget(), nil, 1), 30, 30)
\t}}
\tmult, radius, abil := lowPlunge[c.TalentLvlAttack()], 3.0, "Low Plunge"
\tif high {{ mult, radius, abil = highPlunge[c.TalentLvlAttack()], 5.0, "High Plunge" }}
\tai := info.AttackInfo{{ActorIndex: c.Index(), Abil: abil, AttackTag: attacks.AttackTagPlunge, ICDTag: attacks.ICDTagNone, ICDGroup: attacks.ICDGroupDefault, StrikeType: {strike_type(entry["weapon"])}, Element: {element}, Mult: mult}}
\tc.Core.QueueAttack(ai, combat.NewCircleHitOnTarget(c.Core.Combat.Player(), nil, radius), 40, 40)
\tf := frames.InitAbilSlice(65)
\treturn action.Info{{Frames: frames.NewAbilFunc(f), AnimationLength: 65, CanQueueAfter: 40, State: action.PlungeAttackState}}, nil
}}
"""
    (ROOT / "internal/characters" / slug / "plunge.go").write_text(output)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--character", required=True, help="manifest character slug to generate")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text())
    entries = [
        x for x in manifest["characters"]
        if x["status"] != "existing" and x["name"] == args.character
    ]
    if not entries:
        raise SystemExit(f"unknown imported character: {args.character}")
    for entry in entries:
        record = json.loads((ROOT / entry["source_path"]).read_text())
        data = talent_data(record)
        write_generated(entry, record, data)
        write_base(entry, record, len(data["normal"]))
        write_attack(entry)
        write_charge(entry)
        write_plunge(entry)
    print(f"generated explicit actions for {entries[0]['name']}")


if __name__ == "__main__":
    main()
