#!/usr/bin/env python3
"""Rebuild only the 7.1.51 Mitya/Valeriy/Chernaya numeric tables and catalog."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'character_imports/7.1.51'
HEADER = '// Code generated by scripts/generate_mitya_valeriy_data.py; DO NOT EDIT.\n\n'

def props(values):
    return ','.join('{PropType: model.FightPropType_'+k.upper()+', Value: '+str(v)+'}' for k,v in values.items() if v)
def promos(values):
    return '{MaxLevel:20},'+','.join('{MaxLevel:'+str(l)+',AddProps:[]*model.PromotionAddProp{'+props(v)+'}}' for l,v in zip([40,50,60,70,80,90],values))
blocks=[]
for name,id in [('mitya',10000136),('valeriy',10000137)]:
    d=json.loads((SOURCE/(name+'.json')).read_text()); key=name.capitalize()
    out=HEADER+'package '+name+'\n\nimport ("github.com/genshinsim/gcsim/pkg/core";"github.com/genshinsim/gcsim/pkg/core/keys")\nfunc init(){core.RegisterCharFunc(keys.'+key+',NewChar)}\n'
    for var,s in zip(['normalParams','skillParams','burstParams'],d['skills']):
        rows=[s['promote'][str(i)]['param'] for i in range(15)]
        out+='var '+var+' = [15][25]float64{'+','.join('{'+','.join(map(str,row))+'}' for row in rows)+'}\n'
    (ROOT/f'internal/characters/{name}/data.go').write_text(out)
    sm=d['stats_modifier'];curves={p['type']:p['grow_curve'] for p in sm['prop_grow_curves']}
    blocks.append(f'''keys.{key}: {{Id:{id},Key:"{name}",Rarity:model.QualityType_{d['rarity']},Element:model.ElementType_Electric,WeaponClass:model.WeaponType_{d['weapon']},IconName:"{d['icon']}",Stats:&model.AvatarStatsData{{BaseHp:{d['base_hp']},BaseAtk:{d['base_atk']},BaseDef:{d['base_def']},HpCurve:model.GrowCurveType_{curves['FIGHT_PROP_BASE_HP']},AtkCurve:model.GrowCurveType_{curves['FIGHT_PROP_BASE_ATTACK']},DefCruve:model.GrowCurveType_{curves['FIGHT_PROP_BASE_DEFENSE']},PromoData:[]*model.PromotionData{{{promos(sm['ascension'])}}}}},SkillDetails:&model.AvatarSkillsData{{Attack:{d['skills'][0]['id']},Skill:{d['skills'][1]['id']},Burst:{d['skills'][2]['id']},BurstEnergyCost:60}}}},''')
w=json.loads((SOURCE/'chernaya.json').read_text())
wp=','.join('{PropType:model.FightPropType_'+p['prop_type']+',InitialValue:'+str(p['init_value'])+',Curve:model.GrowCurveType_'+p['type']+'}' for p in w['weapon_prop'])
weapon='keys.Chernaya: {Id:14525,Key:"chernaya",Rarity:5,WeaponClass:model.WeaponType_WEAPON_CATALYST,ImageName:"'+w['icon']+'",BaseStats:&model.WeaponStatsData{BaseProps:[]*model.WeaponProp{'+wp+'},PromoData:[]*model.PromotionData{'+promos([w['ascension'][str(i)] for i in range(1,7)])+'}}},' 
(ROOT/'pkg/catalog/preview_7151.go').write_text(HEADER+'package catalog\nimport("github.com/genshinsim/gcsim/pkg/core/keys";"github.com/genshinsim/gcsim/pkg/model")\nfunc init(){for k,v:=range map[keys.Char]*model.AvatarData{'+''.join(blocks)+'}{CharacterMap[k]=v};for k,v:=range map[keys.Weapon]*model.WeaponData{'+weapon+'}{WeaponMap[k]=v}}\n')

# Keep generated output deterministic and consistent with the Go repository.
import subprocess
subprocess.run(['gofmt', '-w',
    str(ROOT / 'internal/characters/mitya/data.go'),
    str(ROOT / 'internal/characters/valeriy/data.go'),
    str(ROOT / 'pkg/catalog/preview_7151.go')], check=True)
