// Code generated by the origin_data import; DO NOT EDIT.

package roufengyouxian

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() { core.RegisterWeaponFunc(keys.RoufengYouxian, NewWeapon) }
