// Code generated by "pipeline"; DO NOT EDIT.

// passive: Lone Light's Blessing
//
//	When the equipping character unleashes their Elemental Skill, they gain "Gleam of
//	First Light": Every second, increases said character's ATK by between 18% and 36%
//	depending on how much they have traveled over the last 1s while the effect is active.
//	This effect, which lasts 14s, can trigger once every 14s. It is removed when the
//	equipping character leaves the field.
package hereticsmoltenblade

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.HereticsMoltenBlade, NewWeapon)
}
